name: SIDEMADE CI/CD

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest 
        with:
          packages: clang-format
          version: ${{ github.repository }}-style_check
          
      - name: Run style check

        run: clang-format -i src/*.cpp src/*.hpp tests/*.cpp --dry-run -Werror

  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        mode: [Release, Debug]
        compiler: [gcc, clang]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest 
        with:
          packages: clang build-essential cmake libeigen3-dev libboost-all-dev libyaml-cpp-dev
          version: ${{ github.repository }}-${{ matrix.mode }}-${{ matrix.compiler }}

      - name: Build
        run: 
          mkdir build && 
          cd build && 
          cmake -DCMAKE_C_COMPILER=${{ matrix.compiler }} 
                -DCMAKE_CXX_COMPILER=$(if [ "${{ matrix.compiler }}" == "gcc" ]; then echo "g++"; else echo "clang++"; fi) 
                -DCMAKE_BUILD_TYPE=${{ matrix.mode }} .. && 
          make -j4

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.mode }}-${{ matrix.compiler }}
          path: build/*
          retention-days: 1
          if-no-files-found: error

  tests:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        mode: [Release, Debug]
        compiler: [gcc, clang]

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest 
        with:
          packages: clang build-essential cmake libeigen3-dev libboost-all-dev libyaml-cpp-dev
          version: ${{ github.repository }}-${{ matrix.mode }}-${{ matrix.compiler }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.mode }}-${{ matrix.compiler }}
          path: build/

      - name: Run tests
        run: |
          cd build && 
          chmod +x testsidemade sidemade &&
          ctest -j4
